### ISSUE TITLE
Export config module

### ISSUE THREAD

**Issue by pleegor** [PaloAltoNetworks/ansible-pan#12]
Hi, 

While reading documentation, I saw there is import parameter that allows to import previously offloaded config. I am wondering if there is export parameter that will allow to export config files.

**Comment by ivanbojer** [comment]
There is no one at this time. Once we finish this release we will consider adding it.

**Comment by pleegor** [comment]
Thanks @ivanbojer ! I know there are plenty of things on your plate, but I think export parameter will be really helpful.

**Comment by ivanbojer** [comment]
Thank you for the comment and lets keep the issue open so that I can track feature request.

**Comment by pleegor** [comment]
@ivanbojer any update?

**Comment by Ben0001** [comment]
Is there any progress in adding the export parameter?  Thank you for all your hard work.

**Comment by CJloHuK** [comment]
would be nice to have partial config load within that module - very useful.
Thanks

**Comment by arkaraung1993** [comment]
I am also looking for Export config module to panos

**Comment by smolz** [comment]
+1 for this!

**Comment by btorresgil** [comment]
Can you help us understand the use cases for an export module? Are you just trying to export config, or also pcap or other things?  What do you do with the config after export? What format do you need the config in?  Anything that helps us define the requirements would be very helpful, thanks!

**Comment by smolz** [comment]
I use Ansible to backup all of my configs.  My 40 Palo's are just different in my playbook.  I have a workaround in place using the URI module.  
```
tasks:
    - name: Backup Palo
       uri:
        validate_certs: no
        url: https://{{inventory_hostname}}/api/?type=config&action=show&key={{ key }}
        return_content: yes
        method: PUT
      register: result

    - copy:
        content: "{{ result['content'] }}"
        dest: backup/{{ansible_network_os}}/{{inventory_hostname}}-{{date}}.cfg
```

So for what I need is mainly what I get from the fortios_config module:
```
- name: Backup config fortios
      fortios_config:
        host: "{{inventory_hostname}}"
        username: cisco
        password: Cisco123
        backup: yes
        backup_path: "backup/fortios/"
        backup_filename: "{{inventory_hostname}}-{{date}}.cfg"
```
