### ISSUE TITLE
panos_op - 'show interface all' command fails

### ISSUE THREAD

**Issue by smatt241** [PaloAltoNetworks/ansible-pan#123]
**Playbook:**

```
---
- name: Get interface ip mapping
  hosts: physical
  connection: local
  gather_facts: False

  tasks:

  - name: include vault
    include_vars: 'group_vars/vault'
    no_log: True

  - name: show interface all
    panos_op:
      ip_address: '{{ inventory_hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      cmd: 'show interface all'
    register: interface_all
```

**Error:**

The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pandevice/base.py", line 3235, in method
    super_method(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pan/xapi.py", line 951, in op
    self.__type_op(cmd, vsys, extra_qs)
  File "/usr/lib/python3.6/site-packages/pan/xapi.py", line 974, in __type_op
    raise PanXapiError(self.status_detail)
pan.xapi.PanXapiError:  show -> interface -> all needs to have non NULL value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_fsveghc8/ansible_module_panos_op.py", line 134, in main
    xml_output = device.op(cmd, xml=True)
  File "/usr/lib/python3.6/site-packages/pandevice/firewall.py", line 181, in op
    return super(Firewall, self).op(cmd, vsys, xml, cmd_xml, extra_qs, retry_on_peer)
  File "/usr/lib/python3.6/site-packages/pandevice/base.py", line 3372, in op
    element = self.xapi.op(cmd, vsys, cmd_xml, extra_qs, retry_on_peer=retry_on_peer)
  File "/usr/lib/python3.6/site-packages/pandevice/base.py", line 3252, in method
    raise the_exception
pandevice.errors.PanDeviceXapiError:  show -> interface -> all needs to have non NULL value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_fsveghc8/ansible_module_panos_op.py", line 159, in <module>
    main()
  File "/tmp/ansible_fsveghc8/ansible_module_panos_op.py", line 139, in main
    if 'non NULL value' in exc.message:
AttributeError: 'PanDeviceXapiError' object has no attribute 'message'

fatal: [10.53.40.17]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/site-packages/pandevice/base.py\", line 3235, in method\n    super_method(self, *args, **kwargs)\n  File \"/usr/lib/python3.6/site-packages/pan/xapi.py\", line 951, in op\n    self.__type_op(cmd, vsys, extra_qs)\n  File \"/usr/lib/python3.6/site-packages/pan/xapi.py\", line 974, in __type_op\n    raise PanXapiError(self.status_detail)\npan.xapi.PanXapiError:  show -> interface -> all needs to have non NULL value\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_fsveghc8/ansible_module_panos_op.py\", line 134, in main\n    xml_output = device.op(cmd, xml=True)\n  File \"/usr/lib/python3.6/site-packages/pandevice/firewall.py\", line 181, in op\n    return super(Firewall, self).op(cmd, vsys, xml, cmd_xml, extra_qs, retry_on_peer)\n  File \"/usr/lib/python3.6/site-packages/pandevice/base.py\", line 3372, in op\n    element = self.xapi.op(cmd, vsys, cmd_xml, extra_qs, retry_on_peer=retry_on_peer)\n  File \"/usr/lib/python3.6/site-packages/pandevice/base.py\", line 3252, in method\n    raise the_exception\npandevice.errors.PanDeviceXapiError:  show -> interface -> all needs to have non NULL value\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_fsveghc8/ansible_module_panos_op.py\", line 159, in <module>\n    main()\n  File \"/tmp/ansible_fsveghc8/ansible_module_panos_op.py\", line 139, in main\n    if 'non NULL value' in exc.message:\nAttributeError: 'PanDeviceXapiError' object has no attribute 'message'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}

**Comment by jacobsnapp** [comment]
I have successfully run this with python2 on a vagrant-ubuntu-trusty64 connecting to a PA-VM running PAN-OS 8.0.0.
```
---
- name: Test Playbook
  hosts: panos
  gather_facts: false
  vars:
    ansible_python_interpreter:  "/home/vagrant/py2-dev/bin/python2"
  tasks:
    - name: Show Interfaces
      panos_op:
        ip_address: "{{ ip_address }}"
        username: "{{ username }}"
        password: "{{ password }}"
        cmd: 'show interface all'
      register: result
```
