### ISSUE TITLE
panos_security_rule with Panorama: Failed \"present\" apply: Could not find schema node for xpath....

### ISSUE THREAD

**Issue by erics302** [PaloAltoNetworks/ansible-pan#169]
Hi all - I'm running into an issue with the latest panos_security_rule module.  I am using Panorama, and panos_security_rule errors out and the message indicates it's got the wrong xpath.  I've tried with a specific device group, shared and not passing a devicegroup argument, all with no success.
## Environment
- python 2.7.14
- pandevice 0.6.4
- Panorama 8.1.2
- Reverting to the pre-idempotent version of the module I do not have an issue specifying the devicegroup.
- My panorama is a development lab with no firewalls in any of the devicegroups.

## Example 1 code - device group
```
- hosts: PALO
  connection: local
  tasks:
    - name: Add rule
      panos_security_rule:
        ip_address: "{{ ip_address }}"
        api_key: "{{ api_string }}"
        devicegroup: 'zLAB-Apps'
        state: present
        rule_name: "Individual vars test rule"
        source_ip: ["1.1.1.1/32"]
        destination_ip: ["1.1.1.3/32"]
        application: ["TCP_00443_HTTPS"]
```

## Example 1 runtime - device group
```
PLAY [PALO] ************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [plpano01]

TASK [Add rule] ********************************************************************************************************
fatal: [plpano01]: FAILED! => {"changed": false, "msg": "Failed \"present\" apply: Could not find schema node for xpath /config/shared/rulebase/pre-rulebase/security/rules\n"}
        to retry, use: --limit @/home/eric/repo/ansible-role_aci_fw/panos_sec_rule_xpath_issue.retry

PLAY RECAP *************************************************************************************************************
plpano01                   : ok=1    changed=0    unreachable=0    failed=1  
```

API browser on the Panorama shows an xpath of `/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='zLAB-Apps']/pre-rulebase/security`
API browser shows the xpath for shared to be `/config/shared/pre-rulebase/security/rules`

## Example 2 code - shared devicegroup or no devicegroup
I get the same result if I set devicegroup to shared or _when not providing a device group at all_.
```
---
- hosts: PALO
  connection: local
  tasks:
    - name: Add rule
      panos_security_rule:
        ip_address: "{{ ip_address }}"
        api_key: "{{ api_string }}"
        devicegroup: 'shared'
        state: present
        rule_name: "Individual vars test rule"
        source_ip: ["1.1.1.1/32"]
        destination_ip: ["1.1.1.3/32"]
        application: ["TCP_00443_HTTPS"]
```

## Example 2 runtime - shared devicegroup or no devicegroup
```
[OMITTED OUTPUT]

TASK [Add rule] ********************************************************************************************************
fatal: [plpano01]: FAILED! => {"changed": false, "msg": "Device group not found: None"}
        to retry, use: --limit @/home/eric/repo/ansible-role_aci_fw/panos_sec_rule_xpath_issue.retry

PLAY RECAP *************************************************************************************************************
plpano01                   : ok=1    changed=0    unreachable=0    failed=1 
```
