### ISSUE TITLE
configuring ha interface with panos_interface

### ISSUE THREAD

**Issue by chewdevs** [PaloAltoNetworks/ansible-pan#193]
When configuring a HA interface with `panos_interface`, the `zone_name` option should not be mandatory. 

I've tried to use a "ha" zone but it's not working.

The code:
```
- name: configure ha interface
  panos_interface:
    ip_address: "{{ inventory_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    if_name: "ethernet1/1"
    mode: "ha"
    zone_name: "ha"
    enable_dhcp: false
    state: present
  tags: ha
```

The error log:
```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_panos_interface_payload_tjTsdE/__main__.py", line 385, in main
    changed |= set_zone(con, eth, zone_name, zones)
  File "/tmp/ansible_panos_interface_payload_tjTsdE/__main__.py", line 212, in set_zone
    z.create()
  File "/home/adminsip/virtenv/ansible2.7/local/lib/python2.7/site-packages/pandevice/base.py", line 576, in create
    device.active().xapi.set(self.xpath_short(), element, retry_on_peer=self.HA_SYNC)
  File "/home/adminsip/virtenv/ansible2.7/local/lib/python2.7/site-packages/pandevice/base.py", line 3253, in method
    raise the_exception

fatal: [cloud-fw-y02n-prd.cloud.620nm.net]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "adjust_tcp_mss": null, 
            "aggregate_group": null, 
            "api_key": null, 
            "comment": null, 
            "commit": true, 
            "create_default_route": false, 
            "dhcp_default_route_metric": null, 
            "enable_dhcp": false, 
            "if_name": "ethernet1/1", 
            "ip": null, 
            "ip_address": "cloud-fw-y02n-prd.cloud.620nm.net", 
            "ipv4_mss_adjust": null, 
            "ipv6_enabled": null, 
            "ipv6_mss_adjust": null, 
            "link_duplex": null, 
            "link_speed": null, 
            "link_state": null, 
            "lldp_enabled": null, 
            "lldp_profile": null, 
            "management_profile": null, 
            "mode": "ha", 
            "mtu": null, 
            "netflow_profile": null, 
            "netflow_profile_l2": null, 
            "operation": "add", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "username": "iac_user", 
            "vr_name": "default", 
            "vsys_dg": "vsys1", 
            "zone_name": "ha"
        }
    }, 
    "msg": "Failed zone/vr assignment:  ha -> network -> ha unexpected here\n ha -> network is invalid"
}
```
