### ISSUE TITLE
UnboundLocalError: local variable 'xml_output' referenced before assignment

### ISSUE THREAD

**Issue by gliptak** [PaloAltoNetworks/ansible-pan#209]
Running example from https://docs.ansible.com/ansible/latest/modules/panos_op_module.html

```
- name: Test PAN API Key on localhost

  hosts: localhost
  connection: local

  tasks:
  - name: include secrets
    include_vars: 'secrets.yml'
    no_log: True

  - name: show system info
    panos_op:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      cmd: 'show system info'

  - name: show list of all interfaces
    panos_op:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      cmd: 'show interfaces all'
```
fails with
```
PYTHONHTTPSVERIFY=0 ansible-playbook op.yml

PLAY [Test PAN API Key on localhost] ********************************************************************************


TASK [Gathering Facts] **********************************************************************************************

ok: [localhost]

TASK [include secrets] **********************************************************************************************

ok: [localhost]

TASK [show system info] *********************************************************************************************

changed: [localhost]

TASK [show list of all interfaces] **********************************************************************************

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'xml_output' referenced before assignment
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1546535006.03-10885837124296/AnsiballZ_panos_op.py\", line 113, in <module>\n
_ansiballz_main()\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1546535006.03-10885837124296/AnsiballZ_panos_op.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1546535006.03-10885837124296/AnsiballZ_panos_op.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_panos_op_payload_7Fm2hi/__main__.py\", line 159, in <module>\n  File \"/tmp/ansible_panos_op_payload_7Fm2hi/__main__.py\", line 152, in main\nUnboundLocalError: local variable 'xml_output' referenced before assignment\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
        to retry, use: --limit @/home/ec2-user/op.retry

PLAY RECAP **********************************************************************************************************

localhost                  : ok=3    changed=1    unreachable=0    failed=1
```
```
ansible --version
ansible 2.7.5
  config file = None
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']

  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
