### ISSUE TITLE
panos_query_rules: Match by glob pattern and subnet

### ISSUE THREAD

**Issue by megakoresh** [PaloAltoNetworks/ansible-pan#223]
Currently query rules module matches directly by string comparison. This is very inflexible and not very useful (if I knew such exact parameters why would I look up the rule to the begin with?). A much more useful approach would be to try matching by subnet e.g.

destination_ip: 192.168.88.6 would match a rule with destination ip: 192.168.88.0/24 and same for source.

And failing that also match by glob pattern or substring e.g.

destination_ip: 192.168.88.* would match rules with destination ips 192.168.88.0/28 as well as 192.168.88.128/28.

Would also be nice if specifying port range like 4455-5566 would match rules with ports within that range.

An additional argument like `strict` could be used to keep current behaviour, or vice versa - `loose` could be used to apply behaviour like described above.

Since I dont know where to post this, I replicated this issue on ansible as well.

**Comment by shinmog** [comment]
This repo is the right place to post this.

This is interesting.  If we're going to support searches like this, it seems like it would want to be able to do `A or B`, `A and B`, etc.  For simplicity maybe we assume the module won't support parenthesis stuff, so no `(A and B) or C`.

Did you have a mental image of what the playbook task might look like?

**Comment by megakoresh** [comment]
> Did you have a mental image of what the playbook task might look like?

I expected similar functionality to that of Panorama policy search in security policy view. The playbook should look exactly like it does now (maybe with optional extra boolean `loose_match` parameter, like the one you have hard-coded now). However a rule like this

```yaml
from: 192.168.88.0/24
to: 192.168.89.0/24
service: https,http
source_zone: nap
destination_zone: dmz
```

Should be matched by this

```yaml
panos_query_rules:
  destination_ip: 192.168.89.55
  username: '{{ username }}'
  password: '{{ password }}'
  ip_address: '{{ ip_address }}'
```

or this

```yaml
panos_query_rules:
  destination_ip: 192.168*
  username: '{{ username }}'
  password: '{{ password }}'
  ip_address: '{{ ip_address }}'
```

or this

```yaml
panos_query_rules:
  destination_port: 443
  username: '{{ username }}'
  password: '{{ password }}'
  ip_address: '{{ ip_address }}'
```

or this

```yaml
panos_query_rules:
  destination_port: 443
  username: '{{ username }}'
  password: '{{ password }}'
  ip_address: '{{ ip_address }}'
```

You get the idea I hope. Its a rule search, not a direct policy match, I want to be able to specify loosely parameters and get all rules that sort of match them. So that means when the module evaluates a criteria I would like it to try direct match, if that fails, try object match (i.e. if its an IP, check if its in the subnet that is defined in the rule) and if that fails, try just glob pattern match.

I looked over the code and it doesn't seem difficult to implement this, especially if you know what to expect PanOS REST API to return (I have had difficulty with that in the past...).
