### ISSUE TITLE
panos_import.py How to Download image directly from Palo Alto server using this module

### ISSUE THREAD

**Issue by demakkar** [PaloAltoNetworks/ansible-pan#225]
How to Download image directly from Palo Alto server using this or any other module. What should be the server ip address below and file location. 

  panos_import:
    ip_address: 192.168.1.1
    username: admin
    password: admin
    file: /tmp/PanOS_vm-6.1.1
    category: software

**Comment by geraint-jones-nz** [comment]
do you mean `panos_software` ? this will download and deploy he file directly from PA.

```
- name: Install PAN-OS 7.1.16 and restart
  panos_software:
    ip_address: '{{ fw_ip_address }}'
    username: '{{ fw_username }}'
    password: '{{ fw_password }}'
    version: '7.1.16'
    restart: true
```

or if you mean `panos_import` then you need to add `url: http://whatever.com/here`
