### ISSUE TITLE
Feature Request - Add "panos_set" like module

### ISSUE THREAD

**Issue by kquilliam** [PaloAltoNetworks/ansible-pan#237]
I have been using `panos_set` from core to execute quite a few tasks for me that arent covered in this Galaxy role and I fear that the core modules might be abandoned. Is it possible to include the same functionality of this module into the Galaxy role?

https://docs.ansible.com/ansible/latest/modules/panos_set_module.html#panos-set-module

**Comment by shinmog** [comment]
Can you be more specific with what things you were using it for that there aren't `panos_*` modules for yet?

**Comment by trustinger** [comment]
Its probably a bit of a corner case but Im in the middle of a PAN vsys to vPAN migrations, and I find it easier to pull a section of the vsys config via `panos_op`, format it appropriately and then push it with `panos_set` utilizing the list of elements.
```
- panos_set:
    ip_address: "10.249.3.110"
    username: admin
    password: admin
    command: set
    xpath: "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']"
    element: "{{ lookup('lines', 'cat {{ rulebase_file }}') }}"
```
I could iterate through the config after ive pulled it and formatted it and utilize the `panos_security_rule` but it seems more efficient to be able to dump everything in in one go. For ongoing config changes, the modules included here are more than adequate as far as I know.
