### ISSUE TITLE
panos_interface bug

### ISSUE THREAD

**Issue by L1ghtman2k** [PaloAltoNetworks/ansible-pan#247]
When running following playbook:
```
    - name: ethernet1/1 as static in zone outside
      panos_interface:
        ip_address: "192.168.1.1"
        username: "admin"
        password: "admin"
        if_name: "ethernet1/1"
        mode: "layer3"
        ip: ["192.168.8.100/20"]
        enable_dhcp: false
        zone_name: "outside"
```
Ansible throws the folowing Error:
```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_panos_interface_payload_864iXO/__main__.py", line 423, in main
    eth.create()
  File "/usr/local/lib/python2.7/dist-packages/pandevice/base.py", line 2829, in create
    super(VsysOperations, self).create()
  File "/usr/local/lib/python2.7/dist-packages/pandevice/base.py", line 576, in create
    device.active().xapi.set(self.xpath_short(), element, retry_on_peer=self.HA_SYNC)
  File "/usr/local/lib/python2.7/dist-packages/pandevice/base.py", line 3253, in method
    raise the_exception

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "adjust_tcp_mss": null, 
            "aggregate_group": null, 
            "api_key": null, 
            "comment": null, 
            "commit": true, 
            "create_default_route": false, 
            "dhcp_default_route_metric": null, 
            "enable_dhcp": false, 
            "if_name": "ethernet1/1", 
            "ip": [
                "192.168.8.100/20"
            ], 
            "ip_address": "192.168.1.1", 
            "ipv4_mss_adjust": null, 
            "ipv6_enabled": null, 
            "ipv6_mss_adjust": null, 
            "link_duplex": null, 
            "link_speed": null, 
            "link_state": null, 
            "lldp_enabled": null, 
            "lldp_profile": null, 
            "management_profile": null, 
            "mode": "layer3", 
            "mtu": null, 
            "netflow_profile": null, 
            "netflow_profile_l2": null, 
            "operation": "add", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": null, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "vr_name": "default", 
            "vsys_dg": "vsys1", 
            "zone_name": "outside"
        }
    }, 
    "msg": " ethernet1/1 -> layer3 -> dhcp-client constraints failed : DHCP interface IP address must be empty\n ethernet1/1 -> layer3 -> dhcp-client is invalid"
}
```
