### ISSUE TITLE
panos_op with cmd_is_xml: true does not capture the entire output

### ISSUE THREAD

**Issue by SudarshanVK** [PaloAltoNetworks/ansible-pan#250]
I am running a test command using the panos_op module with cmd_is_xml set to true and I see the ansible output is incomplete. In the below case it is leaving out some vital information like the action

My Task

```
    - name: 
      panos_op:
        ip_address: 10.10.100.2
        username: admin
        password: admin
        cmd: "<test><security-policy-match><from>INSIDE</from><to>OUTSIDE</to><source>1.1.1.1</source><destination>2.2.2.2</destination><protocol>6</protocol><destination-port>80</destination-port></security-policy-match></test>"
        cmd_is_xml: true
      register: si
      ignore_errors: true
    - debug: 
        msg: "{{ (si.stdout | from_json)}}"
```

output from palo-alto cli of the equivalent test command
```
<request cmd="op" cookie="1824018934477091" uid="500"><operations><test><security-policy-match><from>INSIDE</from><to>OUTSIDE</to>
<source>1.1.1.1</source><destination>2.2.2.2</destination><protocol>6</protocol><destination-port>80</destination-port></security-
policy-match></test></operations></request>


2019-03-11 11:54:08
<response cmd="status" status="success"><result><msg><line><![CDATA["Deny-Any-Any-Interzone; index: 2" {
        from any;
        source any;
        source-region none;
        to any;
        destination any;
        destination-region none;
        user any;
        category any;
        application/service  any/any/any/any;
        action deny;
        icmp-unreachable: no
        terminal no;
}

]]></line></msg></result></response>

"Deny-Any-Any-Interzone; index: 2" {
        from any;
        source any;
        source-region none;
        to any;
        destination any;
        destination-region none;
        user any;
        category any;
        application/service  any/any/any/any;
        action deny;
        icmp-unreachable: no
        terminal no;
}
```

Output from the module
```
TASK [debug] *********************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "response": {
            "@cmd": "status",
            "@status": "success",
            "result": {
                "rules": {
                    "entry": "Deny-Any-Any-Interzone; index: 2"
                }
            }
        }
    }
}
```

**Comment by shinmog** [comment]
Seems to be working for me...?  Not sure why it's failing for you.

Playbook:
```yaml
- name: Network Playbook
  hosts: fw
  connection: local
  gather_facts: false

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab auth creds
    include_vars: 'vars.yml'
    no_log: 'yes'

  - name: issue250
    panos_op:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      cmd: "<test><security-policy-match><from>L3-trust</from><to>L3-untrust</to><source>1.1.1.1</source><destination>2.2.2.2</destination><protocol>6</protocol><destination-port>80</destination-port></security-policy-match></test>"
      cmd_is_xml: true
    register: si
    ignore_errors: true

  - debug:
      msg: '{{ si.stdout | from_json }}'
```

Output:
```bash
(v3) $ ansible-playbook -i hosts lab.yml 

PLAY [Network Playbook] ************************************************************************************************************************

TASK [PaloAltoNetworks.paloaltonetworks : pip] *************************************************************************************************
ok: [10.8.202.114]

TASK [PaloAltoNetworks.paloaltonetworks : pip] *************************************************************************************************
ok: [10.8.202.114]

TASK [PaloAltoNetworks.paloaltonetworks : pip] *************************************************************************************************
ok: [10.8.202.114]

TASK [Grab auth creds] *************************************************************************************************************************
ok: [10.8.202.114]

TASK [issue250] ********************************************************************************************************************************
changed: [10.8.202.114]

TASK [debug] ***********************************************************************************************************************************
ok: [10.8.202.114] => {
    "msg": {
        "response": {
            "@cmd": "status",
            "@status": "success",
            "result": {
                "rules": {
                    "entry": {
                        "@name": "deny all and log",
                        "action": "deny",
                        "application_service": "0:any/any/any/app-default",
                        "category": "any",
                        "destination": "any",
                        "destination-region": "none",
                        "from": "any",
                        "icmp-unreachable": "no",
                        "index": "2",
                        "source": "any",
                        "source-region": "none",
                        "terminal": "no",
                        "to": "any",
                        "user": "any"
                    }
                }
            }
        }
    }
}

PLAY RECAP *************************************************************************************************************************************
10.8.202.114               : ok=6    changed=1    unreachable=0    failed=0   

(v3) $
```
