### ISSUE TITLE
panos_dag_tags use address-object

### ISSUE THREAD

**Issue by pwe123345** [PaloAltoNetworks/ansible-pan#261]
Hello,

with the use of panos_dag_tags it's not possible to assign tags to existing address-objects. 

Instead, a new object (type registered-ip) is created, when using the ip adress.

**Comment by SudarshanVK** [comment]
Yes, I faced the same issue.
I got around it by creating another task and using panos_set.

**Comment by SudarshanVK** [comment]
something like this. 

```
- name: Set TAG on Network Objects
  panos_set:
      password: "{{ password }}" 
      ip_address: "{{ ip_address }}" 
      username: "{{ username }}" 
      command: set
      xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address/entry[@name='{{ item.destination_ip }}']/tag
      element: <member>OUTSIDE</member>
  when: item.destination_ip | ipaddr("public")
  with_items: "{{ configuration }}"
```
