### ISSUE TITLE
Issue with pan_nat_rule

### ISSUE THREAD

**Issue by jedelman8** [PaloAltoNetworks/ansible-pan#32]
Have tried a few variations including an example from the ansiblie-playbooks repo. Keep getting the following error:

```
fatal: [fw-a]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find schema node for xpath /config/devices/entry[@name='localhost.localdomain']/rulebase/nat/rules\n"}
```

when using any task with `panos_nat_rule`.

Example:
```
      - name: NAT rule for Web SSH
        panos_nat_rule:
          ip_address: "{{ inventory_hostname }}"
          username: "{{ un }}"
          password: "{{pwd}}"
          operation: 'add'
          rule_name: "WebSSH"
          source_zone: ["external"]
          destination_zone: "external"
          source_ip: ["any"]
          destination_ip: ["10.0.0.100"]
          service: "service-tcp-221"
          snat_type: "dynamic-ip-and-port"
          snat_interface: "ethernet1/2"
          dnat_address: "10.0.1.101"
          dnat_port: "22"
          commit: "False"
        tags: nat3
```

Running 7.0.1 PAN-VM and Ansible stable-2.4.

Any help would be appreciated.
