### ISSUE TITLE
panos_lic module test in branch v210

### ISSUE THREAD

**Issue by torstenstern** [PaloAltoNetworks/ansible-pan#335]
Hi, 

I test the panos_lic module in the branch for the new release and I get every time this error.

![Screen Shot 2019-04-16 at 13 40 24](https://user-images.githubusercontent.com/30934288/56206584-07bbb080-604d-11e9-80d9-54b2a0b345b0.png)

I tried to run also the script locally but I get every time the same error.

These are defined in my .yml file.

```
- name: Add some security rules to the firewall and create interfaces
  hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:

   - name: fetch license
     panos_lic:
       ip_address: '{{ ip_address }}'
       username: '{{ username }}'
       password: '{{ password }}'
       auth_code: "XXXXXXX"
     register: result
```

* provider.azurerm: version = "~> 1.24"
* provider.random: version = "~> 2.1"

Thanks Torsten
