### ISSUE TITLE
panos_address_object variables not working when loaded from different sources

### ISSUE THREAD

**Issue by dpflick** [PaloAltoNetworks/ansible-pan#344]
I am loading a set of object variables from the group_vars folder in my inventory and from a group_vars in my task.  The format is identical for both groups and the task that processes them but the variables from the tasks folder cause an invalid IP address where the ones from inventory work.  I literally copied the variables and made the task static and it worked so I am certain that it is not a typo.

Here are the variables from the inventory group_vars file and play that works:
Variable from inventory group_vars file:
```
rddm:
  - object_name: 'TC_RDDM1'
    object_address_type: 'ip-netmask'
    object_value: '10.112.40.130'
    object_description: 'Host A RDDM 1'

  - object_name: 'TC_RDDM2'
    object_address_type: 'ip-netmask'
    object_value: '10.112.40.131'
    object_description: 'Host A RDDM 2'

  - object_name: 'PARIS_RDDM1'
    object_address_type: 'ip-netmask'
    object_value: '10.112.40.212'
    object_description: 'Host B RDDM 1'

  - object_name: 'PARIS_RDDM2'
    object_address_type: 'ip-netmask'
    object_value: '10.112.40.213'
    object_description: 'Host B RDDM 2'
```

and here is the task:
```
- name: Create ECaTS RDDM objects
  panos_address_object:
    ip_address: "{{ fw_ip_address }}"
    username: "{{ fw_username }}"
    password: "{{ fw_password }}"
    vsys: "{{ vsys }}"
    name: "{{ item.object_name }}"
    address_type: "{{ item.object_address_type }}"
    value: "{{ item.object_value }}"
    description: "{{ item.object_description }}"
    state: "present"
    commit: false
  with_items:
    - "{{ rddm }}"
```

And here are the variables from the task group_vars file that don't work:

```
ecats:
  - object_name: 'ECaTS_SFTP_NTP'
    object_address_type: 'ip-netmask'
    object_value: '172.16.1.27'
    object_description: 'ECaTS sFTP and NTP server'

  - object_name: 'ECaTS_API'
    object_address_type: 'ip-netmask'
    object_value: '172.16.3.204'
    object_description: 'ECaTS API server'

  - object_name: 'ECaTS_DNS1_NTP1'
    object_address_type: 'ip-netmask'
    object_value: '172.16.1.51'
    object_description: 'ECaTS DNS and NTP server'

  - object_name: 'ECaTS_DNS1_NTP2'
    object_address_type: 'ip-netmask'
    object_value: '172.16.1.52'
    object_description: 'ECaTS DNS and NTP server'

  - object_name: 'ECaTS_AV'
    object_address_type: 'ip-netmask'
    object_value: '172.16.251.17'
    object_description: 'ECaTS Antivirus server'

  - object_name: 'ECaTS_SSH_RDP'
    object_address_type: 'ip-netmask'
    object_value: '172.16.1.31'
    object_description: 'ECaTS SSH and RDP server'

  - object_name: 'ECaTS_WEST_JUMPBOX'
    object_address_type: 'ip-netmask'
    object_value: '64.58.49.249'
    object_description: 'ECaTS West Jumpbox'

```
And here is the task that fails:
```
 - name: Create ECaTS server objects
   panos_address_object:
     ip_address: "{{ fw_ip_address }}"
     username: "{{ fw_username }}"
     password: "{{ fw_password }}"
     vsys: "{{ vsys }}"
     name: "{{ item.object_name }}"
     address_type: "{{ item.object_address_type }}"
     value: "{{ item.object_value }}"
     description: "{{ item.object_description }}"
     state: "present"
     commit: false
   with_items:
     - "{{ ecats }}"

```
Here is the error:

TASK [ecats_l2l : Create ECaTS server objects] ********************************************************************************************
failed: [atcog-tc-vpnfw] (item={u'object_description': u'ECaTS sFTP and NTP server', u'object_name': u'ECaTS_SFTP_NTP', u'object_address_type': u'ip-netmask', u'object_value': u'172.16.1.27'}) => {"changed": false, "item": {"object_address_type": "ip-netmask", "object_description": "ECaTS sFTP and NTP server", "object_name": "ECaTS_SFTP_NTP", "object_value": "172.16.1.27"}, "msg": " ECaTS_SFTP_NTP -> ip-netmask ['172.16.1.27'] is an invalid ipv4/v6 address\n ECaTS_SFTP_NTP -> ip-netmask is invalid"}
failed: [atcog-tc-vpnfw] (item={u'object_description': u'ECaTS API server', u'object_name': u'ECaTS_API', u'object_address_type': u'ip-netmask', u'object_value': u'172.16.3.204'}) => {"changed": false, "item": {"object_address_type": "ip-netmask", "object_description": "ECaTS API server", "object_name": "ECaTS_API", "object_value": "172.16.3.204"}, "msg": " ECaTS_API -> ip-netmask ['172.16.3.204'] is an invalid ipv4/v6 address\n ECaTS_API -> ip-netmask is invalid"}
failed: [atcog-tc-vpnfw] (item={u'object_description': u'ECaTS DNS and NTP server', u'object_name': u'ECaTS_DNS1_NTP1', u'object_address_type': u'ip-netmask', u'object_value': u'172.16.1.51'}) => {"changed": false, "item": {"object_address_type": "ip-netmask", "object_description": "ECaTS DNS and NTP server", "object_name": "ECaTS_DNS1_NTP1", "object_value": "172.16.1.51"}, "msg": " ECaTS_DNS1_NTP1 -> ip-netmask ['172.16.1.51'] is an invalid ipv4/v6 address\n ECaTS_DNS1_NTP1 -> ip-netmask is invalid"}
failed: [atcog-tc-vpnfw] (item={u'object_description': u'ECaTS DNS and NTP server', u'object_name': u'ECaTS_DNS1_NTP2', u'object_address_type': u'ip-netmask', u'object_value': u'172.16.1.52'}) => {"changed": false, "item": {"object_address_type": "ip-netmask", "object_description": "ECaTS DNS and NTP server", "object_name": "ECaTS_DNS1_NTP2", "object_value": "172.16.1.52"}, "msg": " ECaTS_DNS1_NTP2 -> ip-netmask ['172.16.1.52'] is an invalid ipv4/v6 address\n ECaTS_DNS1_NTP2 -> ip-netmask is invalid"}
failed: [atcog-tc-vpnfw] (item={u'object_description': u'ECaTS Antivirus server', u'object_name': u'ECaTS_AV', u'object_address_type': u'ip-netmask', u'object_value': u'172.16.251.17'}) => {"changed": false, "item": {"object_address_type": "ip-netmask", "object_description": "ECaTS Antivirus server", "object_name": "ECaTS_AV", "object_value": "172.16.251.17"}, "msg": " ECaTS_AV -> ip-netmask ['172.16.251.17'] is an invalid ipv4/v6 address\n ECaTS_AV -> ip-netmask is invalid"}
failed: [atcog-tc-vpnfw] (item={u'object_description': u'ECaTS SSH and RDP server', u'object_name': u'ECaTS_SSH_RDP', u'object_address_type': u'ip-netmask', u'object_value': u'172.16.1.31'}) => {"changed": false, "item": {"object_address_type": "ip-netmask", "object_description": "ECaTS SSH and RDP server", "object_name": "ECaTS_SSH_RDP", "object_value": "172.16.1.31"}, "msg": " ECaTS_SSH_RDP -> ip-netmask ['172.16.1.31'] is an invalid ipv4/v6 address\n ECaTS_SSH_RDP -> ip-netmask is invalid"}
failed: [atcog-tc-vpnfw] (item={u'object_description': u'ECaTS West Jumpbox', u'object_name': u'ECaTS_WEST_JUMPBOX', u'object_address_type': u'ip-netmask', u'object_value': u'64.58.49.249'}) => {"changed": false, "item": {"object_address_type": "ip-netmask", "object_description": "ECaTS West Jumpbox", "object_name": "ECaTS_WEST_JUMPBOX", "object_value": "64.58.49.249"}, "msg": " ECaTS_WEST_JUMPBOX -> ip-netmask ['64.58.49.249'] is an invalid ipv4/v6 address\n ECaTS_WEST_JUMPBOX -> ip-netmask is invalid"}
        to retry, use: --limit @/root/onshore-devops/ecats_l2l.retry

**Comment by shinmog** [comment]
This is working for me.  I'm using the soon to be released v2.1.0, but there's nothing specific about the 2.1.0 `panos_address_object` that should be affecting this.

Before I share my results, looking at your output, it seems like the `ip-netmask` values are being interpreted as a string with the value that looks like a list.  For example, the ECaTS_WEST_JUMPBOX IP is `['64.58.49.249]'` instead of `'64.58.49.249'`.

In any case, here's my config (which is basically your config) and results:

Playbook:
```yml
- name: Network Playbook
  hosts: fw
  connection: local
  gather_facts: false

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab auth creds
    include_vars: 'vars.yml'
    no_log: 'yes'

  - name: Load i344 vars
    include_vars: 'vars_i344.yml'

  - name: Create RDDM objects
    panos_address_object:
      ip_address: '{{ fw_provider.ip_address }}'
      username: '{{ fw_provider.username }}'
      password: '{{ fw_provider.password }}'
      name: '{{ item.object_name }}'
      address_type: '{{ item.object_address_type }}'
      value: '{{ item.object_value }}'
      description: '{{ item.object_description }}'
      commit: false
    with_items:
      - "{{ rddm }}"

  - name: Create ECaTS server objects
    panos_address_object:
      ip_address: '{{ fw_provider.ip_address }}'
      username: '{{ fw_provider.username }}'
      password: '{{ fw_provider.password }}'
      name: "{{ item.object_name }}"
      address_type: "{{ item.object_address_type }}"
      value: "{{ item.object_value }}"
      description: "{{ item.object_description }}"
      commit: false
    with_items:
      - "{{ ecats }}"
```

`vars_i344.yml` variable file:
```yml
rddm:
  - object_name: 'TC_RDDM1'
    object_address_type: 'ip-netmask'
    object_value: '10.112.40.130'
    object_description: 'Host A RDDM 1'

  - object_name: 'TC_RDDM2'
    object_address_type: 'ip-netmask'
    object_value: '10.112.40.131'
    object_description: 'Host A RDDM 2'

  - object_name: 'PARIS_RDDM1'
    object_address_type: 'ip-netmask'
    object_value: '10.112.40.212'
    object_description: 'Host B RDDM 1'

  - object_name: 'PARIS_RDDM2'
    object_address_type: 'ip-netmask'
    object_value: '10.112.40.213'
    object_description: 'Host B RDDM 2'

ecats:
  - object_name: 'ECaTS_SFTP_NTP'
    object_address_type: 'ip-netmask'
    object_value: '172.16.1.27'
    object_description: 'ECaTS sFTP and NTP server'

  - object_name: 'ECaTS_API'
    object_address_type: 'ip-netmask'
    object_value: '172.16.3.204'
    object_description: 'ECaTS API server'

  - object_name: 'ECaTS_DNS1_NTP1'
    object_address_type: 'ip-netmask'
    object_value: '172.16.1.51'
    object_description: 'ECaTS DNS and NTP server'

  - object_name: 'ECaTS_DNS1_NTP2'
    object_address_type: 'ip-netmask'
    object_value: '172.16.1.52'
    object_description: 'ECaTS DNS and NTP server'

  - object_name: 'ECaTS_AV'
    object_address_type: 'ip-netmask'
    object_value: '172.16.251.17'
    object_description: 'ECaTS Antivirus server'

  - object_name: 'ECaTS_SSH_RDP'
    object_address_type: 'ip-netmask'
    object_value: '172.16.1.31'
    object_description: 'ECaTS SSH and RDP server'

  - object_name: 'ECaTS_WEST_JUMPBOX'
    object_address_type: 'ip-netmask'
    object_value: '64.58.49.249'
    object_description: 'ECaTS West Jumpbox'
```

Output:
```bash
(v3) $ ansible-playbook -i hosts i344.yml 

PLAY [Network Playbook] ************************************************************************************************

TASK [PaloAltoNetworks.paloaltonetworks : pip] *************************************************************************
ok: [10.8.202.114]

TASK [PaloAltoNetworks.paloaltonetworks : pip] *************************************************************************
ok: [10.8.202.114]

TASK [PaloAltoNetworks.paloaltonetworks : pip] *************************************************************************
ok: [10.8.202.114]

TASK [Grab auth creds] *************************************************************************************************
ok: [10.8.202.114]

TASK [Load i344 vars] **************************************************************************************************
ok: [10.8.202.114]

TASK [Create RDDM objects] *********************************************************************************************
changed: [10.8.202.114] => (item={'object_name': 'TC_RDDM1', 'object_address_type': 'ip-netmask', 'object_value': '10.112.40.130', 'object_description': 'Host A RDDM 1'})
changed: [10.8.202.114] => (item={'object_name': 'TC_RDDM2', 'object_address_type': 'ip-netmask', 'object_value': '10.112.40.131', 'object_description': 'Host A RDDM 2'})
changed: [10.8.202.114] => (item={'object_name': 'PARIS_RDDM1', 'object_address_type': 'ip-netmask', 'object_value': '10.112.40.212', 'object_description': 'Host B RDDM 1'})
changed: [10.8.202.114] => (item={'object_name': 'PARIS_RDDM2', 'object_address_type': 'ip-netmask', 'object_value': '10.112.40.213', 'object_description': 'Host B RDDM 2'})
[DEPRECATION WARNING]: Classic provider params are deprecated; use "provider" instead. This feature will be removed in 
version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [Create ECaTS server objects] *************************************************************************************
changed: [10.8.202.114] => (item={'object_name': 'ECaTS_SFTP_NTP', 'object_address_type': 'ip-netmask', 'object_value': '172.16.1.27', 'object_description': 'ECaTS sFTP and NTP server'})
changed: [10.8.202.114] => (item={'object_name': 'ECaTS_API', 'object_address_type': 'ip-netmask', 'object_value': '172.16.3.204', 'object_description': 'ECaTS API server'})
changed: [10.8.202.114] => (item={'object_name': 'ECaTS_DNS1_NTP1', 'object_address_type': 'ip-netmask', 'object_value': '172.16.1.51', 'object_description': 'ECaTS DNS and NTP server'})
changed: [10.8.202.114] => (item={'object_name': 'ECaTS_DNS1_NTP2', 'object_address_type': 'ip-netmask', 'object_value': '172.16.1.52', 'object_description': 'ECaTS DNS and NTP server'})
changed: [10.8.202.114] => (item={'object_name': 'ECaTS_AV', 'object_address_type': 'ip-netmask', 'object_value': '172.16.251.17', 'object_description': 'ECaTS Antivirus server'})
changed: [10.8.202.114] => (item={'object_name': 'ECaTS_SSH_RDP', 'object_address_type': 'ip-netmask', 'object_value': '172.16.1.31', 'object_description': 'ECaTS SSH and RDP server'})
changed: [10.8.202.114] => (item={'object_name': 'ECaTS_WEST_JUMPBOX', 'object_address_type': 'ip-netmask', 'object_value': '64.58.49.249', 'object_description': 'ECaTS West Jumpbox'})

PLAY RECAP *************************************************************************************************************
10.8.202.114               : ok=7    changed=2    unreachable=0    failed=0   

(v3) $ 
```
