### ISSUE TITLE
panos_static_route is broken.  Nexthop required but option does not exist.

### ISSUE THREAD

**Issue by dpflick** [PaloAltoNetworks/ansible-pan#345]
Variables:

```
routes:
  - name: 'ECATS-L2L-172.16.1'
    destination: '172.16.1.0/24'

  - name: 'ECATS-L2L-172.16.3'
    destination: '172.16.3.0/24'

  - name: 'ECATS-L2L-172.16.251'
    destination: '172.16.251.0/24'

  - name: 'ECATS-L2L-64.58.49.249'
    destination: '64.58.49.249/32'
```

Task:

```
- name: Building routes for tunnel
  panos_static_route:
    ip_address: '{{ fw_ip_address }}'
    username: '{{ fw_username }}'
    password: '{{ fw_password }}'
    virtual_router: '{{ vrouter }}'
    name: '{{ item.name }}'
    destination: '{{ item.destination }}'
    interface: 'tunnel.80'
  with_items:
    - '{{ routes }}'
```

Error:

failed: [atcog-tc-vpnfw] (item={u'destination': u'172.16.1.0/24', u'name': u'ECATS-L2L-172.16.1'}) => {"changed": false, "item": {"destination": "172.16.1.0/24", "name": "ECATS-L2L-172.16.1"}, "msg": " ECATS-L2L-172.16.1 -> nexthop is invalid"}
failed: [atcog-tc-vpnfw] (item={u'destination': u'172.16.3.0/24', u'name': u'ECATS-L2L-172.16.3'}) => {"changed": false, "item": {"destination": "172.16.3.0/24", "name": "ECATS-L2L-172.16.3"}, "msg": " ECATS-L2L-172.16.3 -> nexthop is invalid"}
failed: [atcog-tc-vpnfw] (item={u'destination': u'172.16.251.0/24', u'name': u'ECATS-L2L-172.16.251'}) => {"changed": false, "item": {"destination": "172.16.251.0/24", "name": "ECATS-L2L-172.16.251"}, "msg": " ECATS-L2L-172.16.251 -> nexthop is invalid"}
failed: [atcog-tc-vpnfw] (item={u'destination': u'64.58.49.249/32', u'name': u'ECATS-L2L-64.58.49.249'}) => {"changed": false, "item": {"destination": "64.58.49.249/32", "name": "ECATS-L2L-64.58.49.249"}, "msg": " ECATS-L2L-64.58.49.249 -> nexthop is invalid"}

Searching through the module, nexthop nor next_hop exists in the code.
