### ISSUE TITLE
panos_ipsec_profile broken.  Not possible to set required dh_group.

### ISSUE THREAD

**Issue by dpflick** [PaloAltoNetworks/ansible-pan#346]
Task:

```
- name: Add IPSec crypto config to the firewall
  panos_ipsec_profile:
    ip_address: '{{ fw_ip_address }}'
    username: '{{ fw_username }}'
    password: '{{ fw_password }}'
    state: 'present'
    name: 'AES256-SHA1-nopfs'
    encryption: ['aes-256-cbc']
    authentication: 'sha1'
    dhgroup: 'no-pfs'
    lifetime_hrs: '1'
    commit: 'False'
```

Tried setting dhgroup or dh_group to any setting (no_pfs, group2, group5, etc) and the command fails.

fatal: [atcog-tc-vpnfw]: FAILED! => {"changed": false, "msg": " AES256-SHA1-nopfs -> dh-group '['group2']' is not an allowed keyword\n AES256-SHA1-nopfs -> dh-group is invalid"}

If you try omitting, it will fail with group2 which is the default.
