### ISSUE TITLE
panos_nat_rule is not idempotent when omitting parameters

### ISSUE THREAD

**Issue by MrDanao** [PaloAltoNetworks/ansible-pan#351]
### Version

```
PAN-OS v8.1.4

Ansible v2.7.10
+ ansible-pan v2.1.0

Python v2.7.15rc1
+ pan-python v0.14.0
+ pandevice v0.9.1
```

### Affected module(s)

- panos_nat_rule

#### Task

```yaml
- name: add nat rules
  panos_nat_rule:
    provider: "{{ fw_provider }}"
    rule_name: "{{ item.key }}"
    description: "{{ item.value.description | default(omit) }}"
    tag: "{{ item.value.tag | default(omit) }}"
    source_zone: "{{ item.value.src_zone }}"
    source_ip: "{{ item.value.src_ip }}"
    to_interface: "{{ item.value.to_interface | default(omit) }}"
    service: "{{ item.value.service | default(omit) }}"
    destination_zone: "{{ item.value.dest_zone }}"
    destination_ip: "{{ item.value.dest_ip }}"
    snat_type: "{{ item.value.snat_type | default(omit) }}"
    snat_address_type: "{{ item.value.snat_address_type | default(omit) }}"
    snat_static_address: "{{ item.value.snat_static_address | default(omit) }}"
    snat_dynamic_address: "{{ item.value.snat_dynamic_address | default(omit) }}"
    snat_interface: "{{ item.value.snat_interface | default(omit) }}"
    snat_interface_address: "{{ item.value.snat_interface_address | default(omit) }}"
    snat_bidirectional: "{{ item.value.snat_bidirectional | default(omit) }}"
    dnat_address: "{{ item.value.dnat_address | default(omit) }}"
    dnat_port: "{{ item.value.dnat_port | default(omit) }}"
    state: present
    commit: True
  with_dict: "{{ nat_rules }}"
```

#### Variable

```yaml
nat_rules:

  nat-rule-name-1:
    src_zone:
      - untrust
    src_ip:
      - any
    to_interface: ethernet1/1
    service: any
    dest_zone: untrust
    dest_ip:
      - address-object-1
    dnat_address: address-object-2

  nat-rule-name-2:
    src_zone:
      - trust
    src_ip:
      - address-object-3
    to_interface: any
    service: any
    dest_zone: untrust
    dest_ip:
      - address-object-4
    snat_type: dynamic-ip-and-port
    snat_address_type: translated-address
    snat_dynamic_address:
      - address-object-5
    tag:
      - tag-1
```

### Expected Behavior

Idempotency from the second `ansible-playbook` run: `changed=0`.

### Actual Behavior

Ansible output shows changes at the end of the second `ansible-playbook` run: `changed=1`.

I also omit `panos_security_rule`'s parameters like `description`, `tag_name` and I have no idempotency issues.
