### ISSUE TITLE
panos_ipsec_tunnel throws encoding error

### ISSUE THREAD

**Issue by odysseus107** [PaloAltoNetworks/ansible-pan#366]
When using the module 'panos_ipsec_tunnel' in any way, e.g. with the example in the library, the following error appears:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: Non-ASCII character '\xe2' in file /tmp/ansible_panos_ipsec_tunnel_payload_ZBtNZ6/__main__.py on line 83, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

fatal: [host]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1558371755.74-105008737331240/AnsiballZ_panos_ipsec_tunnel.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1558371755.74-105008737331240/AnsiballZ_panos_ipsec_tunnel.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1558371755.74-105008737331240/AnsiballZ_panos_ipsec_tunnel.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_panos_ipsec_tunnel_payload_ZBtNZ6/__main__.py\", line 82\nSyntaxError: Non-ASCII character '\\xe2' in file /tmp/ansible_panos_ipsec_tunnel_payload_ZBtNZ6/__main__.py on line 83, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by shinmog** [comment]
This is working for me.  Perhaps something is corrupted in your library code?

  ist.yml:

```yml
- name: Network Playbook
  hosts: fw
  connection: local
  gather_facts: false

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab auth creds
    include_vars: 'vars.yml'
    no_log: 'yes'

  - name: Create ipsec tunnel
    panos_ipsec_tunnel:
      provider: '{{ fw_provider }}'
      name: 'IPSecTunnel-Ansible'
      tunnel_interface: 'tunnel.2'
      ak_ike_gateway: 'IKEGW-Ansible'
      ak_ipsec_crypto_profile: 'IPSec-Ansible'
      state: 'present'
      commit: false
```

```bash
(v9) $ ansible-playbook -i hosts ist.yml 

PLAY [Network Playbook] *****************************************************************************************************************

TASK [PaloAltoNetworks.paloaltonetworks : Install pan-python required library] **********************************************************
ok: [10.8.202.114]

TASK [PaloAltoNetworks.paloaltonetworks : Install pandevice required library] ***********************************************************
ok: [10.8.202.114]

TASK [PaloAltoNetworks.paloaltonetworks : Install xmltodict required library] ***********************************************************
ok: [10.8.202.114]

TASK [Grab auth creds] ******************************************************************************************************************
ok: [10.8.202.114]

TASK [Create ipsec tunnel] **************************************************************************************************************
changed: [10.8.202.114]

PLAY RECAP ******************************************************************************************************************************
10.8.202.114               : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

(v9) $ 
```

**Comment by odysseus107** [comment]
Thanks for your quick answer. We checked several modules and versions in our Vagrant VM and finally found that we run Python 2.7 per default and Python 3.6 fixes this issue.

**Comment by shinmog** [comment]
@odysseus107 

Looking at that PEP link in your first comment, it seems that your python 2.7 is complaining that there isn't an encoding declared in the module, but the PEP states that there should be an assumed ASCII encoding if it isn't defined...

Could you try modifying the module code to have this as the second line in the file and see if it works under python 2.7 for you?

```python
# -*- coding: utf-8 -*-
```

**Comment by odysseus107** [comment]
yep, this change works with Python 2.7.

**Comment by shinmog** [comment]
@odysseus107 

Thanks for checking, I'll update the modules to do this.

**Comment by odysseus107** [comment]
Thank you, too!

**Comment by pixelicous** [comment]
> Could you try modifying the module code to have this as the second line in the file and see if it works under python 2.7 for you?
> 
> ```python
> # -*- coding: utf-8 -*-
> ```

I got this error today as well, running ubuntu 18.04 on windows 10 in WSL.. running python 2.7.15
Adding the encoding line as the 2nd line in the yaml didnt help :(
`
File \"/tmp/ansible_Wds25p/ansible_module_panos_ipsec_tunnel.py\", line 82\nSyntaxError: Non-ASCII character '\\xe2' in file /tmp/ansible_Wds25p/ansible_module_panos_ipsec_tunnel.py on line 83, but no encoding declared;`

```yaml
  - name: ipsec tunnel
    when: only_ike == false
    panos_ipsec_tunnel:
      provider: '{{ provider }}'
      name: 'somename'
      tunnel_interface: 'tunnel.2'
      ike_gtw_name: 'ikegw'
      ipsec_profile: 'someprofile'
      enable_tunnel_monitor: true
      tunnel_monitor_dest_ip: "1.2.3.4"
      commit: False
      state: present

```
