### ISSUE TITLE
Problem with panos_op provider

### ISSUE THREAD

**Issue by SmUrF3R5** [PaloAltoNetworks/ansible-pan#433]
I am trying to use this module and seem to be having issues getting it to recognize the new module over the default one i think.

Ansible Tower 3.4.2
Ansible 2.8.4

Cloned this repo and put in roles/PaloAltoNetworks.paloaltonetworks directory

I am referencing this documentationbut am having a problem with the providers parameters
https://ansible-pan.readthedocs.io/en/latest/modules/panos_op_module.html

The yml I am running looks like this. I still get the Deprication Warning so I know i must be doing something wrong. How do I get this to use the new one?
```
- name: clear sessions
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:  
  - name: 'show session all filter source {{ source_ip_address }}'
    panos_op: 
      provider: { ip_address: 'my_firewall',password: '{{ paloalto_password }}',username: '{{ paloalto_username }}'}     
      cmd: '<show><session><all><filter><source>{{ source_ip_address }}</source></filter></all></session></show>'
      cmd_is_xml: true
    register: result 
  - name: returned output in the default JSON format
    debug: msg='{{ result.stdout }}'



ansible-playbook 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /tmp/awx_3733_QFYxtN/tmpyenkOm as it did not pass it's verify_file() method
Parsed /tmp/awx_3733_QFYxtN/tmpyenkOm inventory source with script plugin

[DEPRECATION WARNING]: panos_op is kept for backwards compatibility but usage 
is discouraged. The module documentation details page may explain more about 
this rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAYBOOK: clear_sessions.yml ***************************************************
1 plays in clear_sessions.yml
META: ran handlers
TASK [show session all filter source xxx.xxx.xxx.xxx] *****************************
task path: /var/lib/awx/projects/_64__ansibleipcpaloaltofirewall/clear_sessions.yml:10
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1568839779.48-120938252401084 `" && echo ansible-tmp-1568839779.48-120938252401084="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1568839779.48-120938252401084 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/panos/_panos_op.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-3OprjL9/tmpQHHFSB TO /var/lib/awx/.ansible/tmp/ansible-tmp-1568839779.48-120938252401084/AnsiballZ__panos_op.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1568839779.48-120938252401084/ /var/lib/awx/.ansible/tmp/ansible-tmp-1568839779.48-120938252401084/AnsiballZ__panos_op.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1568839779.48-120938252401084/AnsiballZ__panos_op.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1568839779.48-120938252401084/ > /dev/null 2>&1 && sleep 0'


fatal: [localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "cmd": "<show><session><all><filter><source>{{ source_ip_address }}</source></filter></all></session></show>", 
            "cmd_is_xml": true, 
            "provider": {
                "ip_address": "myfirewall", 
                "password": "THIS IS IN CLEAR TEXT!!!!", 
                "username": "my_admin"
            }
        }
    }, 
    "msg": "Unsupported parameters for (panos_op) module: cmd_is_xml, provider Supported parameters include: api_key, cmd, ip_address, password, username"
}

```

**Comment by shinmog** [comment]
@SmUrF3R5 
You're specifying the provider dict as a python dict instead of a YAML dict; try it like this:

```yaml
- name: clear sessions
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:  
  - name: 'show session all filter source {{ source_ip_address }}'
    panos_op: 
      provider:
        ip_address: 'my_firewall'
        password: '{{ paloalto_password }}'
        username: '{{ paloalto_username }}'}     
      cmd: '<show><session><all><filter><source>{{ source_ip_address }}</source></filter></all></session></show>'
      cmd_is_xml: true
    register: result 
  - name: returned output in the default JSON format
    debug: msg='{{ result.stdout }}'
```
