### ISSUE TITLE
Changing password erases the userid on a PA-220

### ISSUE THREAD

**Issue by pchiquit** [PaloAltoNetworks/ansible-pan#460]
## Describe the bug
When executing he following playbook:
```
- name: Change user password using the password itself
  panos_administrator:
    provider: 
      ip_address: "{{ ansible_host }}"
      username: '{{ credential_username }}'
      password: '{{ credential_password }}'
    admin_username: '{{ credential_username }}'
    admin_password: "{{ credential_stagingPassword }}"
    #superuser: true
    commit: true
  #no_log: true
  delegate_to: localhost
```
I get the following failure:
```
ASK [PanOS : Change user password using the password itself] *********************************************************************************************************************************************************
fatal: [rtptest-pa-220b.raleigh.ibm.com -> localhost]: FAILED! => {"changed": false, "msg": "Failed commit: URLError: code: 403 reason: Invalid Credential"}
```
After that action, the userid doesn't show up on the PanOS interface or on the CLI. If I do a `config audit` I can see that the entries for the userid now only have the phash field. So it goes from:
```
 test  { permissions { role-based { superuser yes; } } phash ****}
```
 to 
```
test  { phash ********; } ”
```
## Expected behavior

I would expect the other fields to stay and the password to be changed and the commit to work.

## Current behavior

Userid is disabled/vanished, commit does not work.

## Steps to reproduce

Describe above.
1.
2.
3.
4.

## Context

Trying to automate password change of local userids on Palo Alto firewall devices.

## Your Environment
ansible 2.9.2
Latest version of Pan-module installed yesterday.
