### ISSUE TITLE
panos_aggrigate_interface error with global name 'eth' is not defined

### ISSUE THREAD

**Issue by CrimsonBinome24** [PaloAltoNetworks/ansible-pan#468]
Attempting to create AE group using the following:

Ansible Version 2.9.4

ansible-playbook relevant code.

```
    - name: Setup remote  AE Group
      panos_aggregate_interface:
        provider: "{{ provider }}"
        if_name: "ae1"
        mode: "layer2"
        state: "present"
        zone_name: "untrust"
        commit: "no"
```
Output:

traceback, use -vvv. The error was: NameError: global name 'eth' is not defined
fatal: [M-PA-INET]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/*username*/.ansible/tmp/ansible-tmp-1582663638.4-239589164367437/AnsiballZ_panos_aggregate_interface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/*username*/.ansible/tmp/ansible-tmp-1582663638.4-239589164367437/AnsiballZ_panos_aggregate_interface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/*username*/.ansible/tmp/ansible-tmp-1582663638.4-239589164367437/AnsiballZ_panos_aggregate_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_aggregate_interface', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_panos_aggregate_interface_payload_YqW63O/ansible_panos_aggregate_interface_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_aggregate_interface.py\", line 289, in <module>\n  File \"/tmp/ansible_panos_aggregate_interface_payload_YqW63O/ansible_panos_aggregate_interface_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_aggregate_interface.py\", line 258, in main\nNameError: global name 'eth' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
