### ISSUE TITLE
Allow for add or update operation

### ISSUE THREAD

**Issue by ivanbojer** [PaloAltoNetworks/ansible-pan#88]
Currently add or update operation is exclusive. This is done in order to force users be aware of the configuration before they change it. This prove to be inconvenient in CI/CD pipelines where a lot of the rules are being configured in the ad-hoc fashion. 

We need to have ability to add or update objects irrespective if they exist or not. This can be done either by overloading add or update operation or by coming up with completely new operator (e.g. upset).

**Comment by synthesizerpatel** [comment]
There's a slightly deeper problem with this approach, I came up with a way to handle this with conditionals like this

```
- name: Search for shared address object
  panos_object:
    ip_address: "{{ PAN_HOST }}"
    username: "{{ PAN_USER }}"
    api_key: "{{ PAN_KEY }}"
    address: "{{ item.address | default (omit) }}"
    address_type: "{{ item.address_type | default (omit) }}"
    addressobject: "{{ item.addressobject | default (omit) }}"
    operation: find
  register: result
  ignore_errors: yes

- name: Add a new record
  panos_object:
    ip_address: "{{ PAN_HOST }}"
    username: "{{ PAN_USER }}"
    api_key: "{{ PAN_KEY }}"
    operation: add
    address: "{{ item.address | default (omit) }}"
    addressobject: "{{ item.addressobject | default (omit) }}"
    address_type: "{{ item.address_type | default (omit) }}"
    description: "{{ item.description | default (omit) }}"
    static_value: "{{ item.static_value | default (omit) }}"
  when: result is failed

- name: Update an existing record
  panos_object:
    ip_address: "{{ PAN_HOST }}"
    username: "{{ PAN_USER }}"
    api_key: "{{ PAN_KEY }}"
    operation: update
    address: "{{ item.address | default (omit) }}"
    addressobject: "{{ item.addressobject | default (omit) }}"
    address_type: "{{ item.address_type | default (omit) }}"
    description: "{{ item.description | default (omit) }}"
    static_value: "{{ item.static_value | default (omit) }}"
  when: result is succeeded
```

This works somewhat like you'd expect/want - if the addressobject already exists (you can find it) ,then we set operation: update, otherwise operation: add.

The only problem is - 'updating' isn't idempotent. When you update a value, if the values you're using are exactly the same as what you just added or updated - it applies the change *again*.
