### ISSUE TITLE
Question about backing up running config

### ISSUE THREAD

**Issue by farhadkam** [PaloAltoNetworks/ansible-pan#90]
Hi Experts,

Is there any way to backup panos running config using ansible?

Thanks and sorry for this as I could not find any module in Ansible Documentation for backing up Panos.

**Comment by dmitryzykov** [comment]
I've created a napalm-ansible module `napalm_get_config` for creating backup of running config. It works for panos well.

role
```yaml
- name: install napalm
  pip:
    name: "{{ item }}"
    state: latest
  with_items: 
    - napalm
    - napalm-ansible
    - napalm-panos

- name: backup config
  napalm_get_config:
    hostname: "{{ inventory_hostname }}"
    username: "{{ username }}"
    dev_os: "{{ os }}"
    password: "{{ password }}"
    dest: "{{ backup_path }}/{{ inventory_hostname }}"
    strip_comments: "{{ backup_strip_comments }}"
  register: config
  environment: 
    PYTHONHTTPSVERIFY: 0 # do not verify ssl certs at panos devices
```

ansible.cfg
```
[defaults]
library = /usr/lib/python2.7/site-packages/napalm_ansible
```

playbook
```
- hosts: all
  gather_facts: no
  connection: local
  roles:
    - backup
```

https://github.com/napalm-automation/napalm
https://github.com/napalm-automation/napalm-ansible
https://github.com/napalm-automation/napalm-ansible/pull/131
https://github.com/napalm-automation-community/napalm-panos/
